### PR TITLE
Database Query Interface Implementation

### PR DESCRIPTION
**Pull request by howawong**
Usage: 
```python
container.public_database.query(Query(...))
container.public_database.save(record)
```

### CODE REVIEW

**Comment by howawong** [comment]
@rickmak any preference on doc generator?

**Comment by rickmak** [comment]
I only have experience on sphinx + docstrings. Is it okay for you?

**Comment by howawong** [comment]
sphinx is fine

**Comment by howawong** [comment]
Let me write up docstring for query.py and predicate.py before merging.

**Comment by chpapa** [comment]
Ping on this, avoid dragging PR too long so no one know how to merge it in future? XD

**Comment by howawong** [comment]
Okay, let me write up docstring first

**Comment by howawong** [comment]
@rickmak  please review the doc and merge it.

**Comment by howawong** [comment]
Connects #144

**Comment by rickmak** [comment]
@carmenlau we will want to maintain the backward import capability on the `encoding`.

**Pull request merged**
