### PR TITLE
Rename `config` to `skyconfig`

### PR DESCRIPTION
**Pull request by ben181231**
This PR tries to avoid the followings:
1. naming collision of `skygear.config`, which will be implemented in #70
2. some import renaming, i.e. `from .. import config as skyconfig`

### CODE REVIEW

**Comment by oursky-travis** [comment]
@ben181231, thanks for your PR! By analyzing the annotation information on this pull request, we identified @rickmak to be a potential reviewer

**Comment by cheungpat** [comment]
I'd suggest you call it another name, or merge it with `settings`

**Comment by rickmak** [comment]
Merge with `settings` make sense to me.

**Comment by ben181231** [comment]
Okay. Let's merge it to `settings`.

**Comment by ben181231** [comment]
Close this PR. The change will be included in PR #74.

**Pull request closed without merging**
