### PR TITLE
Avoid sending heartbeat when handling request

### PR DESCRIPTION
**Pull request by b123400**
connect https://github.com/SkygearIO/skygear-server/issues/342
connect https://github.com/SkygearIO/skygear-server/pull/349

Also refactored the run_message_loop function

### CODE REVIEW

**Comment by oursky-travis** [comment]
@b123400, thanks for your PR! By analyzing the history of the files in this pull request, we identified @limouren to be a potential reviewer.

**Comment by rickmak** [comment]
When I put plugin idle for few minute, all worker will become `Ticking non-registered worker`....

**Comment by rickmak** [comment]
I encounter using current master of https://github.com/skygeario/chat and https://github.com/skygear-demo/react-chat-demo

I still figuring why. Will try to provide a meaningful test case.

**Comment by b123400** [comment]
Updated, it was issue with heartbeat timeout

**Comment by rickmak** [comment]
Merge via 4f6531b

**Pull request closed without merging**
