### PR TITLE
Send request from worker

### PR DESCRIPTION
**Pull request by b123400**
connect https://github.com/SkygearIO/skygear-server/issues/304
Based on https://github.com/SkygearIO/py-skygear/pull/123

It creates a new one-off worker to send the request, then shut it down.

### CODE REVIEW

**Comment by rickmak** [comment]
1. Rebase it

**Comment by rickmak** [comment]
Rebase it... I cannot leave meaningful inline comment. So I leave it here.

In stead of making a closure in ZmqTransport and inject it into the worker. May be following kind of code is more straight forward to understand?

```
class OneOffWorker(Worker):

    def __init__(self, z_context, addr, stopper, registry=None, action_name=None, payload={}):
        Worker.__init__(self, z_context, addr, stopper, registry=None)
        // save state.

    def run():
        // call send_action and put the value into self._result

    def join(self):
        Thread.join(self)
        return self._result


class ZmqTransport(CommonTransport):

    def send_action(self, action_name, payload, url, timeout):
        worker = threading.current_thread()
        if isinstance(worker, Worker):
            # Nested request
            result = worker.send_action(action_name, payload)
            return json.loads(result)

        new_worker = OneOffWorker(
            self._context,
            self._addr,
            self.stopper,
            action_name=action_name,
            payload=payload
        )
        new_worker.start()
        result = new_worker.join()
        return json.loads(result)

```

**Comment by b123400** [comment]
Rewritten to follow your design and added test case

**Comment by rickmak** [comment]
Merge into zmq-multiplex via 0b6ab24

**Pull request closed without merging**
